name: lgtm-image-action
author: lazy-actions
description: 'Post LGTM image when reviewer approves pull request'
inputs:
  repo-token:
    description: 'Specify GITHUB_TOKEN to access GitHub API'
    required: true
  favorite-image:
    description: 'Your favorite image urls'
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'thumbs-up'
  color: 'yellow'